version: '3'
services:
    mvc-db:
      image: postgres:12.4
      environment:
        - POSTGRES_DB=daycare 
        - POSTGRES_PASSWORD=dogdaycare 
        - POSTGRES_USER=dogdaycare
      ports:
        - 5432:5432
    facility-db:
      image: postgres:12.4
      environment:
        - POSTGRES_DB=facility
        - POSTGRES_PASSWORD=dogdaycare
        - POSTGRES_USER=dogdaycare
      ports:
        - 5431:5432
    eureka:
      image: steeltoeoss/eureka-server
      ports:
        - 8761:8761
      depends_on:
        - facility-db
        - mvc-db
    spring-boot-admin:
      environment:
        - EUREKA_SERVICE_URL=http://eureka:8761
      image: "hananiel/spring-boot-admin-eureka-sample"
      ports:
        - "8889:8080"
      depends_on:
        - eureka
    # FacilityService:
    #   build:
    #     context: api/FacilityService/
    #   image: tscrypter/facilityservice:latest
    #   ports:
    #     - "8081:80"
    #   environment:
    #     - "Postgres__Client__Host=facility-db"
    #     - "Postgres__Client__Port=5432"
    #     - "Postgres__Client__Username=dogdaycare"
    #     - "Postgres__Client__Password=dogdaycare"
    #     - "Postgres__Client__DataBase=facility"
    #     - "ASPNETCORE_ENVIRONMENT=Development"
    #   depends_on:
    #     - spring-boot-admin
    # mvc:
    #   build:
    #     context: ui/MvcDogDaycare/
    #   image: tscrypter/dogdaycaremvc:latest
    #   ports:
    #     - "8080:80"
    #   environment:
    #     - "Postgres__Client__Host=mvc-db"
    #     - "Postgres__Client__Port=5432"
    #     - "Postgres__Client__Username=dogdaycare"
    #     - "Postgres__Client__Password=dogdaycare"
    #     - "Postgres__Client__DataBase=daycare"
    #     - "ASPNETCORE_ENVIRONMENT=Development"
    #   depends_on:
    #     - FacilityService