// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ui.MvcDogDaycare.Data;

namespace MvcDogDaycare.Migrations
{
    [DbContext(typeof(DogDaycareContext))]
    [Migration("20201023041818_Initial Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MvcDogDaycare.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Dog");
                });

            modelBuilder.Entity("MvcDogDaycare.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DropOffDttm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickUpDttm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("MvcDogDaycare.Models.Reservation", b =>
                {
                    b.HasOne("MvcDogDaycare.Models.Dog", "Pet")
                        .WithMany("Reservations")
                        .HasForeignKey("PetId");
                });
#pragma warning restore 612, 618
        }
    }
}
